server:
  port: 8080
spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INFO/**
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-allow-others: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #启用SQL语句的日志记录
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: create
  mail:
    host: smtp.mail.qq.com
    port: 587
    userName: 1324073644@qq.com
    password: 123456


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    static-path-pattern: /**
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html

  web:
    resources:
      static-locations: classpath:/static/
  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always
      schema-locations: classpath:db/schema.sql
      platform: h2
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shugram.demo.controller

knife4j:
  enable: true
  setting: zh_cn


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

backup:
  email: axinawang@163.com